import keyMirror from 'keymirror';

export default keyMirror({
  API_CALL: null,

  AUTHENTICATION_LOGIN_FAILURE: null,
  AUTHENTICATION_LOGIN_REQUEST: null,
  AUTHENTICATION_LOGIN_SUCCESS: null,
  AUTHENTICATION_REGISTRATION_REQUEST: null,
  AUTHENTICATION_REGISTRATION_SUCCESS: null,
  AUTHENTICATION_REGISTRATION_FAILURE: null,
  AUTHENTICATION_REDIRECT: null,
  AUTHENTICATION_REGISTRATION_SUCCESS: null,
  FORM_PUSH_VALUES: null,
  FORM_REMOVE_VALUES: null,
  FORM_UPDATE_FIELD_VALUE: null,
  FORM_UPDATE_VALUES: null,
});
